version: '3.8'

services:
  cypress:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - ./docker-reports:/app/cypress/reports
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
